### ISSUE TITLE
Copy?

### ISSUE THREAD

**Issue by AlexFlipnote** [mangobots/discord_bot.py#2]
Why did you copy my bot framework and posted it as your own?

**Comment by Natsukiworks** [comment]
Yeah you’re right, I’ll delete that, One of my friends said to do that,
wasn’t really sure though. Sorry for that, didn’t mean to copy or anything

**Comment by AlexFlipnote** [comment]
If you really want to "copy" my bot, I suggest to fork it to follow the LICENSE on the bot source code. 👍

**Comment by Natsukiworks** [comment]
Yeah, I should of thought before hand, hopefully I didn’t cause any harm.
Have a good day sir

**Comment by AlexFlipnote** [comment]
Don't worry, there's no harm, just wanted to make sure you follow the license ❤️ 
Thank you for understanding and have a great day.
